### ISSUE TITLE
JS Cart creation

### ISSUE THREAD

**Issue by gEndelf** [nac-jac/nac-jac.github.io#15]
* create JS cart with methods:
 * addProduct(productId, price, productName, qnty) - add product to cart
 * removeProduct(productId) - remove product
 * updateProduct(productId, qty) - update
 * totalPrice() - calculate products price from shopping cart - **calculated on server side**
 * clean() - drop all products from shopping cart
 * all() - returns all products from shopping cart or empty array 

---

save shopping cart to cookies / or local storage - and restore

**Comment by gEndelf** [comment]
@AleksandrPrykhodko we already have PR, bind cart methods on the page

**Comment by uncoder** [comment]
@gEndelf OK

**Comment by gEndelf** [comment]
done

**Comment by gEndelf** [comment]
@AleksandrPrykhodko plz avoid code/template duplication
Code block for checkout included 4 times! (4 pages)
Fix it

**Comment by AleksandrPrykhodko** [comment]
Fixed, plz review PR

**Comment by gEndelf** [comment]
done
